apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernet
  namespace: ghost
spec:
  secretName: kubernet-crt-secret
  dnsNames:
  - www.kubernet.dev
  - kubernet.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
