apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ghost-personal
  namespace: ghost
spec:
  storageClassName: managed-premium
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
