apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ghost-personal
  namespace: ghost
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
