name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'
                
      - name: Set AKS context
        uses: Azure/aks-set-context@v4
        with:
          resource-group: rg-aks-centralus
          cluster-name: aks-centralus
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v5
        with:
          namespace: ghost
          manifests: k8s/deployment.yaml
          images: docker.pkg.github.com/${{ github.repository }}/ghost
